### ISSUE TITLE
status become hidden

### ISSUE THREAD

**Issue by bau720123** [Telerik-Verified-Plugins/WKWebView#6]
hi @EddyVerbruggen 
before use this plugin in PGB，the status bar will show by use 3rd status plugin
but...
after use it，the status bar become hidden (full screen)，and can't control it anymore

**Comment by EddyVerbruggen** [comment]
Hi @bau720123, I just fixed an issue where the statusbar wasn't a 'separate block' as you mentioned earlier. Check out 0.3.5.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
just check once again

I use phonegap build 3.7 + "org.apache.cordova.statusbar" 0.1.10 + "com.telerik.plugins.wkwebview" 0.3.8 => but still not work...
http://www.littlebau.com/20141211/01.PNG

**Comment by EddyVerbruggen** [comment]
@bau720123 can you share your project with me perhaps, so I can reproduce and fix it for you?

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
this is the full PGB build code
www.littlebau.com/3.7.1.zip

**Comment by EddyVerbruggen** [comment]
Hi @bau720123 could you please try it by using the config.xml? Especially for `StatusBarOverlaysWebView` because the plugin determines the height of the webview upon initialization. 

config.xml:
```xml
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="StatusBarStyle" value="lightcontent" />
```

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
is "StatusBarOverlaysWebView" and "StatusBarStyle" are suitable by using PGB (build.phonegap.com) ?

anyway...tried many times...but still not work

**Comment by EddyVerbruggen** [comment]
AFAIK yes

**Comment by bau720123** [comment]
so you mean is after you use my sample code "3.7.1.zip" and use these two attribute
problem solved ? right ?

**Comment by EddyVerbruggen** [comment]
No I asked you to try it with those properties on PGB. But I'm guessing it didn't work unfortunately ;)

**Comment by bau720123** [comment]
ya...I really tried for many times
but still not work...
well...if I delete this plugin Temporary，the status bar and webview become normal
anyway...just feedback these information
if something update，I will told you，thanks again
