### ISSUE TITLE
External url fails, no entry in Resources tab in Safari Web Inspector (ios)

### ISSUE THREAD

**Issue by JeremyColton** [Telerik-Verified-Plugins/WKWebView#86]
Hi,
I am using PhoneGap 3.6.3, not using their build system. Building via XCode 6.1.1.
Before using your plugin, my app can send ajax requests to my server ok.

After installing your latest plugin my initial ajax request to my web server fails.  There's nothing in the Web Inspector other than a red line for my ajax request. No response failure info.

I've enabled CORS on my server to all domains.

What can I do?

Many thanks
Jeremy

**Comment by EddyVerbruggen** [comment]
Can you share the server endpoint with me?

**Comment by JeremyColton** [comment]
http://10.0.0.5:8080/<my domain>/public/loginViaFacebook

**Comment by EddyVerbruggen** [comment]
Since that's an internal server I can't check the headers unfortunately. Can you post a server response including the headers?

**Comment by JeremyColton** [comment]
There is no response. Just a red line in Web Inspector's Network Requests tab.  It never hits the server. There are no response headers (see attached screenshot).

I think the request is being swallowed by the embedded web server from the WKWebView pluing??

![screen shot 2015-03-18 at 2 53 46 pm](https://cloud.githubusercontent.com/assets/2919478/6709109/0525d7c0-cd7f-11e4-9bd3-72da9985d1c3.png)

**Comment by EddyVerbruggen** [comment]
ok, have you checked the accesslog of the server?

**Comment by JeremyColton** [comment]
Nope, where is the access log of the embedded web server that you added in this plugin?

**Comment by EddyVerbruggen** [comment]
I meant the accesslog of your server at http://10.0.0.5:8080/ - the one at the client wouldn't help you as the server response seems the problem.

**Comment by JeremyColton** [comment]
Ah ok, I enabled my access logs on my remote server. Without your plugin, it has entries.  With your plugin, no entries.  So the remote server is never being contacted when using your plugin.

XCode debug for my app says the following which suggests the local/embedded server is running ok:

2015-03-18 15:14:02.139 ScoochUp_iOS_PG363_WKWebView[1205:609034] [CDVTimer][TotalPluginStartup] 97.660005ms
[INFO] GCDWebServer started on port 12344 and reachable at http://10.0.0.4:12344/
2015-03-18 15:14:02.146 ScoochUp_iOS_PG363_WKWebView[1205:609034] Started http daemon: http://10.0.0.4:12344/ 

Any other ideas?

Cheers for your time and fast replies!

**Comment by JeremyColton** [comment]
Do you know when the official Phonegap WKWebkitView will be released?

**Comment by EddyVerbruggen** [comment]
I'm not sure but if CORS is the problem it will have the same issues.

Btw, in your screnshot there is a red exclamation mark. If you click it (or the 'Console' icon), do you see any additional errors/warnings?

**Comment by JeremyColton** [comment]
Well-spotted!  It says it's a CORS issue.  I am debugging how I've configured it on my server and will update this issue...

**Comment by JeremyColton** [comment]
Ok, I have fixed my CORS config on my external server :)

On successful login to my server, my server sets a JSESSION param in a cookie in the response. Which I see in the response header. See the attached screenshot (url to loginViaFacebook)
![screen shot 2015-03-19 at 1 02 10 pm](https://cloud.githubusercontent.com/assets/2919478/6729143/382e17f4-ce38-11e4-8153-5d065a2ad65a.png)


But, subsequent requests from my app to to my server are missing this JSESSION cookie.  See 2nd screenshot.  Is your embedded server sending managing cookies ok?
![screen shot 2015-03-19 at 1 03 07 pm](https://cloud.githubusercontent.com/assets/2919478/6729160/552fc0dc-ce38-11e4-8d4a-1d8498b1a908.png)

**Comment by JeremyColton** [comment]
Does your embedded server forward the browser's cookies?

**Comment by EddyVerbruggen** [comment]
Hi @JeremyColton I don't have time right away to check it, but you could Google for 'GCDWebServer cookies' as that's the embedded webserver we're using.

**Comment by JeremyColton** [comment]
Fiddler confirms that without your plugin, http requests sent from my app to my external server after authentication have a JSESSION cookie HTTP header included.  With your plugin, these requests don't have this cookie header.  I've googled for a reason but found nothing.  It could be with how you route requests thru it from the WKWebView? I am not skilled to resolve this, sorry.  Do you see your cookies being forwarded as expected?

**Comment by EddyVerbruggen** [comment]
No as I've never used co okies but rather managed sessions (if any) by passing custom headers which I reasd from responses and add to requests manually. I'll need to study this.

**Comment by JeremyColton** [comment]
When you say set 'manually', you mean at the javascript level on the ajax request?

**Comment by EddyVerbruggen** [comment]
Yes, as an XHR header to jquery's .ajax() function f.i.

**Comment by JeremyColton** [comment]
I have fixed it after reading http://stackoverflow.com/questions/2870371/why-is-jquerys-ajax-method-not-sending-my-session-cookie

Server side: a) I had to set the specific allowed CORS origin "http://localhost:12344" for the embedded web server AND allow 'xhrFields'. Client side: a) add 'xhrFields' to my ajax request.  

Now the cookie is being passed in the http header.

**Comment by JeremyColton** [comment]
Now my ionic keyboard behaves strangely, there's no vertical scroll bar in my list of items, no photos are retrieved from the camera or album!  No time to fix stuff that once worked, I will revert to the standard UIWebView for now...

**Comment by velochy** [comment]
I'm seeing something very similar, but even with CORS origin set to "http://localhost:12344" and Allow-Credentials set on server, and withCredentials set on xhr requests, the cookies are still not being stored or sent back.

Looking at the webview through safari devtools, this is what is happening:

/api/authenticate - goes through successfully, coming back with Set-Cookie header as it should
/api/student/ - request is sent without a Cookie header, reaches the server that way (checked server log) and comes back as unauthorized

If I disable server-side headers, the webview complains that Allow-Credentials is not sent for both requests, so I assume that means that withCredentials is indeed set for xhr requests. 

So it seems the trouble is the Set-Cookie just being ignored and the cookie not being stored for the remote site.

I also read that some browsers blocked cookies from sites that had not been visited directly, so I ran a redirect loop with local -> remote server web page -> back to local. Sadly, it did not change anything.

I'd be happy to provide any additional details that may help get to the bottom of this. The old UIWebView leaks memory and is slow for my webapp and I would really want to upgrade to WKWebView as soon as possible.

**Comment by rayshan** [comment]
@velochy This seems to be the issue: https://github.com/Telerik-Verified-Plugins/WKWebView/issues/197
